AllCops:
  NewCops: enable
  TargetRubyVersion: 3
  Exclude:
    - "mitamae/plugins/**/*"

Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

# No mruby support
Style/PercentLiteralDelimiters:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false
