dist: bionic
os: linux
language: ruby

services:
  - docker

addons:
  apt:
    update: true

install:
  - sudo apt install -y curl ca-certificates
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - sudo apt update -qq
  - sudo apt install --no-install-recommends vagrant

script:
  - vagrant up
after_script:
  - vagrant destroy -f
