language: ruby

services:
  - docker

addons:
  apt:
    update: true

install:
  - sudo apt install -y curl ca-certificates
  - curl -o /tmp/vagrant.deb -L https://releases.hashicorp.com/vagrant/${VERSION}/vagrant_${VERSION}_x86_64.deb
  - sudo dpkg -i /tmp/vagrant.deb

script:
  - vagrant up
after_script:
  - vagrant destroy -f
