ubuntu_version = "24.04"
ubuntu_suite = "noble"
username = "moritzheiber"
gsettings_user = "{username}"

ppas = [
  "git-core/ppa",
  "mozillateam/ppa"
]

[remote_files.mcfly]
version = "0.9.3"
url = "https://github.com/cantino/mcfly/releases/download/v{.version}/mcfly-v{.version}-x86_64-unknown-linux-musl.tar.gz"
checksum = "be0d3c1e0253189a5d834767231c2a4d206f077f4184699ac7069482ed9c6453"
target = "/usr/bin/mcfly"
artifact = "mcfly"

[[files]]
name = "firefox-global-policies"
source = "files/firefox_policies.js" 
target = "/etc/firefox/policies/policies.json"
mode = "0644"

[[files]]
name = "microsoft-repo-preferences"
regexp = "repo_reenable_on_distupgrade=\"true\""
content = "repo_reenable_on_distupgrade=\"false\""
target = "/etc/default/microsoft-edge"

[[files]]
name = "streamdeck-access"
source = "files/streamdeck_rules_udev"
target = "/etc/udev/rules.d/60-streamdeck.rules"
mode = "0644"

[[files]]
name = "proposed-priority"
content = """
Package: *
Pin: release a=noble-proposed
Pin-Priority: 400
"""
target = "/etc/apt/preferences.d/proposed-priority-400"
mode = "0644"

[[files]]
name = "mozilla-ppa"
content = """
Package: firefox thunderbird
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
"""
target = "/etc/apt/preferences.d/mozillateam-priority-1001"
mode = "0644"

[[files]]
name = "mozilla-security"
content = """
Package: firefox thunderbird
Pin: release o=LP-PPA-ubuntu-mozilla-security
Pin-Priority: 1001
"""
target = "/etc/apt/preferences.d/ubuntu-mozilla-security-priority-1001"
mode = "0644"

[[files]]
name = "mozilla-no-snap"
content = """
Package: firefox* thunderbird*
Pin: release o=Ubuntu*
Pin-Priority: -1
"""
target = "/etc/apt/preferences.d/mozilla-no-snap"
mode = "0644"

[[files]]
name = "no-install-recommends"
content = """
APT::Install-Recommends "false";
APT::Get::Always-Include-Phased-Updates "true";
"""
target = "/etc/apt/apt.conf.d/99custom"
mode = "0644"

[[files]]
name = "user-avatar"
source = "files/avatar.png"
target = "/usr/local/share/avatars/avatar.png"
mode = "0644"

[[files]]
name = "1password-enable-native-messaging-host"
source = "files/firefox_local_apparmor"
target = "/etc/apparmor.d/local/usr.bin.firefox"
mode = "0644"

[[files]]
name = "npmrc"
content = """
prefix=/home/{username}/.local/npm
"""
target = "/home/{username}/.npmrc"
owner = "{username}"
group = "{username}"
mode = "0644"

[packages]
ruby = "latest"
ruby-dev = "latest"
build-essential = "latest"
git = "latest"
urlscan = "latest"
mutt = "latest"
gnupg = "latest"
unzip = "latest"
dkms = "latest"
"libdbus-glib-1-dev" = "latest"
whois = "latest"
htop = "latest"
"i965-va-driver" = "latest"
"libvdpau-va-gl1" = "latest"
jq = "latest"
wireguard = "latest"
unrar = "latest"
w3m = "latest"
gimp = "latest"
pinentry-curses = "latest"
"libsecret-1-dev" = "latest"
mosh = "latest"
signal-desktop = "latest"
wl-clipboard = "latest"
silversearcher-ag = "latest"
shellcheck = "latest"
python3-pip = "latest"
python3-dev = "latest"
ttf-mscorefonts-installer = "latest"
fonts-font-awesome = "latest"
fonts-powerline = "latest"
libpam-u2f = "latest"
neovim = "latest"
libssl-dev = "latest"
code = "latest"
docker-ce = "latest"
gh = "latest"
"gstreamer1.0-plugins-bad" = "latest"
totem = "latest"
heif-gdk-pixbuf = "latest"
heif-thumbnailer = "latest"
xdg-desktop-portal-gnome = "latest"
ripgrep = "latest"
git-delta = "latest"
firefox = "latest"
golang-go = { state = "uninstalled" }
thunderbird =  { state = "uninstalled" }
pidgin =  { state = "uninstalled" }
apport-gtk =  { state = "uninstalled" }

[repositories.docker]
uris = ["https://download.docker.com/linux/ubuntu"]
signed_by = ["https://download.docker.com/linux/ubuntu/gpg"]
suites = ["noble"]
components = ["stable"]
architectures = ["amd64"]

[repositories.signal]
uris = ["https://updates.signal.org/desktop/apt"]
suites = ["xenial"]
signed_by = ["https://updates.signal.org/desktop/apt/keys.asc"]
components = ["main"]
architectures = ["amd64"]

[repositories.hashicorp]
uris = ["https://apt.releases.hashicorp.com"]
suites = ["jammy"]
signed_by = ["https://apt.releases.hashicorp.com/gpg"]
components = ["main"]
architectures = ["amd64"]

[repositories.gh]
uris = ["https://cli.github.com/packages"]
suites = ["stable"]
signed_by = ["https://cli.github.com/packages/githubcli-archive-keyring.gpg"]
components = ["main"]
architectures = ["amd64"]

[repositories.microsoft-edge-vscode]
uris = [
  "https://packages.microsoft.com/repos/code",
  "https://packages.microsoft.com/repos/edge"
]
suites = ["stable"]
signed_by = ["https://packages.microsoft.com/keys/microsoft.asc"]
components = ["main"]
architectures = ["amd64"]

[gsettings]
enabled = { schema = "org.gnome.system.location", value = "true" }
automatic-timezone = { schema = "org.gnome.desktop.datetime", value = "true" }
clock-format = { schema = "org.gnome.desktop.interface", value = "24h" }
clock-show-date = { schema = "org.gnome.desktop.interface", value = "true" }
clock-show-weekday = { schema = "org.gnome.desktop.interface", value = "true" }
color-scheme = { schema = "org.gnome.desktop.interface", value = "prefer-dark" }
enable-hot-corners = { schema = "org.gnome.desktop.interface", value = "false" }
show-battery-percentage = { schema = "org.gnome.desktop.interface", value = "true" }
disable-disconnected-notifications = { schema = "org.gnome.nm-applet", value = "true" }
disable-connected-notifications = { schema = "org.gnome.nm-applet", value = "true" }
night-light-enabled = { schema = "org.gnome.settings-daemon.plugins.color", value = "true" }
night-light-schedule-automatic = { schema = "org.gnome.settings-daemon.plugins.color", value = "true" }
autohide = { schema = "org.gnome.shell.extensions.dash-to-dock", value = "false" }
dock-fixed = { schema = "org.gnome.shell.extensions.dash-to-dock", value = "false" }
intellihide = { schema = "org.gnome.shell.extensions.dash-to-dock", value = "false" }
dash-max-icon-size = { schema = "org.gnome.shell.extensions.dash-to-dock", value = "32" }
preferred-monitor = { schema = "org.gnome.shell.extensions.dash-to-dock", value = "0" }
per-window = { schema = "org.gnome.desktop.input-sources", value = "false" }
sources = { schema = "org.gnome.desktop.input-sources", value = "[('xkb', 'us')]" }
xkb-options = { schema = "org.gnome.desktop.input-sources", value = "['compose:ralt']" }
natural-scroll = { schema = "org.gnome.desktop.peripherals.mouse", value = "true" }
two-finger-scrolling-enabled = { schema = "org.gnome.desktop.peripherals.touchpad", value = "true" }
disable-microphone = { schema = "org.gnome.desktop.privacy", value = "false" }
report-technical-problems = { schema = "org.gnome.desktop.privacy", value = "false" }
click-policy = { schema = "org.gnome.nautilus.preferences", value = "single" }
default-folder-viewer = { schema = "org.gnome.nautilus.preferences", value = "icon-view" }
search-filter-time-type = { schema = "org.gnome.nautilus.preferences", value = "last_modified" }
show-delete-permanently = { schema = "org.gnome.nautilus.preferences", value = "true" }
custom-keybindings = { schema = "org.gnome.settings-daemon.plugins.media-keys", value = "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']" }
logout = { schema = "org.gnome.settings-daemon.plugins.media-keys", value = "@as []" }
terminal = { schema = "org.gnome.settings-daemon.plugins.media-keys", value = "['<Super>Return']" }
binding = { schema = "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding", path = "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/", value = "<Primary><Alt>Delete" }
command = { schema = "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding", path = "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/", value = "systemctl suspend" }
name = { schema = "org.gnome.settings-daemon.plugins.media-keys.custom-keybinding", path = "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/", value = "Suspend" }
show-home = { schema = "org.gnome.shell.extensions.ding", value = "false" }
