#!/bin/bash

set -Eeux -o pipefail

declare -a services=("udev" "geoclue")

_handle_restart() {
  local value
  value="${*}"

  for service in "${services[@]}" ; do
    if [ "${value}" == "${service}" ] ; then
      echo "Would've restarted ${service} using systemd"
      exit 0
    fi
  done

  echo "I don't mock the service you're trying to restart!"
  exit 1
}

CMD=${1:-}
shift || true

case "${CMD}" in
  restart) _handle_restart "$@" ;;
  *) exit 0;
esac
